### ISSUE TITLE
CakePHP 3 Installer problem

### ISSUE THREAD

**Issue by krusty999** [cakephp/plugin-installer#23]
I'm doing a fresh install of CakePHP 3 and having this error message:

[ErrorException]
include(/var/www/cake3/vendor/cakephp/plugin-installer/src//Installer/PluginInstaller.php): failed to open stream: No such file or directory

I'm on a fresh install on a vagrant box using this command for install

composer create-project --prefer-dist -s dev cakephp/app cake3

taken from CakePHP 3 Book.

I see a double / on ...src//Installer... part of the path.

I check and the PluginInstaller.php file is in the correct location.

![image](https://cloud.githubusercontent.com/assets/100788/5989416/4762f362-a966-11e4-8bb5-d4c558e4bd34.png)

**Comment by markstory** [comment]
If you run with the `--debug` option what is the stacktrace on that error?

**Comment by krusty999** [comment]
I hope this help.

![image](https://cloud.githubusercontent.com/assets/100788/5991408/743f08ec-a9cc-11e4-9bda-a04690740ca9.png)

**Comment by ADmad** [comment]
@krusty999 In your app's composer.json could you try changing `"plugin-installer":"*"` to `"plugin-installer":"dev-master"` and then run `composer update --prefer-dist`.

**Comment by dereuromark** [comment]
Might be worth mentioning that this is just temporary, until a new release has been tagged.

**Comment by markstory** [comment]
Closing as the `//` has been fixed.

**Comment by krusty999** [comment]
Hi, on composer.json I changed line 12 from `"cakephp/plugin-installer": "*"`to `"cakephp/plugin-installer": "dev-master"`and run `sudo composer update --prefer-dist --verbose` as Admad suggest. 

Now I'getting a new [RuntimeException]

![image](https://cloud.githubusercontent.com/assets/100788/5993423/e0bc5b7a-aa2e-11e4-8a3d-34fc4fdfe68a.png)

I've tryed a fresh install and previous error still persist.

**Comment by dereuromark** [comment]
Try to delete the vendors folder content and freshly run composer.

**Comment by krusty999** [comment]
I deleted the `vendor` folder and run ´sudo composer update --prefer-dist --verbose´ and this is the result

![image](https://cloud.githubusercontent.com/assets/100788/5993489/3000bd28-aa31-11e4-893e-828a268368e2.png)

I checked and `vendor` doesn't exists

![image](https://cloud.githubusercontent.com/assets/100788/5993495/86c19236-aa31-11e4-987d-1107e15976c6.png)

**Comment by dereuromark** [comment]
I said content as in "in the folder", not the folder itself. That folder should be present. Even though it would be auto-created if the system allows it.

**Comment by ADmad** [comment]
@krusty999 Btw running composer with `sudo` isn't a good idea. It would be better if you try installing in a folder your logged in user has write permissions to.

**Comment by krusty999** [comment]
Bad luck :( no CakePHP 3 for me this weekend.

There is a vagrant box that just works with CakePHP 3?

**Comment by markstory** [comment]
It looks like composer isn't able to create directories. Have you been able to install dependencies for any other projects on your vm?

**Comment by krusty999** [comment]
Hi, an update on this.

Now installation is working.

The problem with composer wasn't able to create directories was because a conflitc with my Antivirus Software (Avast Free), seems to be scanning files on shared folders. So I put and exception to vagrant project folder and now is working ok.

Thanks to each one for you help.

**Comment by markstory** [comment]
Great to hear you figured out the issue :smile:
